version: '3.8'

services:
  db:
    image: postgres:16.3
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: mydatabase
    volumes:
      - ./database/init-db.sql:/docker-entrypoint-initdb.d/init-db.sql
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  app:
    build: .
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_USER: myuser
      DB_PASSWORD: mypassword
      DB_DATABASE: mydatabase
      JWT_SECRET: your_jwt_secret_here
    ports:
      - "9000:9000"
    volumes:
      - ./client/uploads:/app/client/uploads
    depends_on:
      - db

volumes:
  pgdata: